name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run tests
      run: |
        pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.ACTION_PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine bump2version
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Get current version
      id: current_version
      run: echo "::set-output name=version::$(grep -m1 version src/datasience_methods/__init__.py | cut -d'"' -f2)"
    - name: Bump version
      run: |
        bump2version patch
    - name: Get new version
      id: new_version
      run: echo "::set-output name=version::$(grep -m1 version src/datasience_methods/__init__.py | cut -d'"' -f2)"
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_PAT }}
      run: |
        git push https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:main
        git push --tags https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/*